// Catalogue des cours

const ZOOM_LINK = "https://univ-lille-fr.zoom.us/j/4477131791?pwd=QPA5WINhRT8gImdExYVP1Nj0ARhYUK.1";
window.courses = [

  // ————————————————————————————————————
  // 1) Alphabétisation
  // ————————————————————————————————————
  {
    slug: "alphabetisation-homme",
    password: "ALPHAH25",
    titre: "Séminaire d'alphabétisation arabe",
    enseignant: "Muʿallim Ilies",
    description: "Corrections et explications du livre d’alphabétisation Al-Iqraiyyah.",
    tags: ["Arabe", "Débutant"],
    zoomUrl: ZOOM_LINK,
    //pdfView: "assets/Livre-dalphabetisation-iqraiyyah-2025.pdf",
    replays: [
    { titre: "Cours du 19/02", url: "https://drive.google.com/file/d/1yz_iBMlRzkwoyRB141lUcUu2PfQpFH6L/preview" },
    { titre: "Cours du 22/02", url: "https://drive.google.com/file/d/1p4jnGSq0-no5INqpfS9wekSRyGH9rTUV/preview" },
    { titre: "Cours du 26/02", url: "https://drive.google.com/file/d/1rEqmZamLk8IDoIAz8ogKix8S6wvsao43/preview" },
    { titre: "Cours du 01/03", url: "https://drive.google.com/file/d/1wEN19ypaIC3giEDOzAQggUX3EVnkppSf/preview" },
    { titre: "Cours du 05/03", url: "https://drive.google.com/file/d/1OUVj7_bDaWRd07KHSytfvUArEBM0R5_t/preview" }
  ],

    supports: [
      { titre: "Fiche n°1 — bâ, tâ, thâ et voyelles courtes",
        cours: "https://www.youtube.com/watch?v=telKHgVI3cw",
        correction: "https://www.youtube.com/watch?v=1a8Deyyr4MM",
        pdf: "assets/alpha/Fiche 1.pdf"},
      { titre: "Fiche n°2 — bâ, tâ, thâ et tanwîn",
        cours: "https://www.youtube.com/watch?v=kbGpVe481qU",
        correction: "https://www.youtube.com/watch?v=PZ_BLGF5Vyw",
        pdf: "assets/alpha/Fiche 2.pdf"},
      { titre: "Fiche n°3 — bâ, tâ, thâ et voyelles longues",
        cours: "https://www.youtube.com/watch?v=W_1VXnDcWVA",
        correction: "https://www.youtube.com/watch?v=bzGV8lp8G3Y",
        pdf: "assets/alpha/Fiche 3.pdf"},
      { titre: "Fiche n°4 — djîm, hâ et khâ",
        cours: "https://www.youtube.com/watch?v=eI7Iu2QGe5w",
        correction: "https://www.youtube.com/watch?v=Wab5xt4Tv6A",
        pdf: "assets/alpha/Fiche 4.pdf"},
      { titre: "Fiche n°5 — dâl, dhâl, râ, zay et soukoûn (P1)",
        cours: "https://www.youtube.com/watch?v=SPujRXH5wi",
        correction: "https://www.youtube.com/watch?v=dW4ZMgQcmME",
        pdf: "assets/alpha/Fiche 5.pdf"},
      { titre: "Fiche n°6 — dâl, dhâl, râ, zay et soukoûn (P2)",
        cours: "https://www.youtube.com/watch?v=SPujRXH5wi",
        correction: "https://www.youtube.com/watch?v=Fj58XweaRXk",
        pdf: "assets/alpha/Fiche 6.pdf"},
      { titre: "Fiche n°7 — sîn, chîn et chaddah",
        cours: "https://www.youtube.com/watch?v=YBR9s2cxj6o",
        correction: "https://www.youtube.com/watch?v=bhZwuEx1v4k",
        pdf: "assets/alpha/Fiche 7.pdf"},
      { titre: "Fiche n°8 — sâd, dâd, tâ’, thâ’ (P1)",
        cours: "https://www.youtube.com/watch?v=cy4BvAk55Aw",
        correction: "https://www.youtube.com/watch?v=7VTXvAiMSiI",
        pdf: "assets/alpha/Fiche 8.pdf"},
      { titre: "Fiche n°9 — sâd, dâd, tâ’, thâ’ (P2)",
        cours: "https://www.youtube.com/watch?v=uKYdQrzMuVo",
        correction: "https://www.youtube.com/watch?v=9ZjzYnXBUmI",
        pdf: "assets/alpha/Fiche 9.pdf"},
      { titre: "Fiche n°10 — ‘ayn et ghayn",
        cours: "https://www.youtube.com/watch?v=gw9jClQKlkY",
        correction: "https://www.youtube.com/watch?v=OyIAqtUhqGk",
        pdf: "assets/alpha/Fiche 10.pdf"},
      { titre: "Fiche n°11 — fâ’, qâf et kâf",
        cours: "https://www.youtube.com/watch?v=0hBvtgiluS0",
        correction: "https://www.youtube.com/watch?v=mq5hsDv3Rb4",
        pdf: "assets/alpha/Fiche 11.pdf"},
      { titre: "Fiche n°12 — lâm, mîm et nûn",
        cours: "https://www.youtube.com/watch?v=NUCfloC37bE",
        correction: "https://www.youtube.com/watch?v=00iblSVm0O4",
        pdf: "assets/alpha/Fiche 12.pdf"},
      { titre: "Fiche n°13 — hâ’, wâw et yâ’",
        cours: "https://www.youtube.com/watch?v=2OYUMgfRo-A",
        correction: "https://www.youtube.com/watch?v=vbfJzv2bdbg",
        pdf: "assets/alpha/Fiche 13.pdf"},
      { titre: "Fiche n°14 — Particularités coraniques",
        cours: "https://www.youtube.com/watch?v=krD5zZtSjMo",
        correction: "https://www.youtube.com/watch?v=wpATBOMbOrg",
        pdf: "assets/alpha/Fiche 14.pdf"},
      { titre: "Fiche n°15 — Ligatures (wasâlat)",
        cours: "https://www.youtube.com/watch?v=IdLoS2ezOrc",
        correction: "https://www.youtube.com/watch?v=ql_QWLYd7EA",
        pdf: "assets/alpha/Fiche 15.pdf"}
    ]
  },

  // ————————————————————————————————————
  // 2) Tajwīd
  // ————————————————————————————————————
  {
    slug: "alphabetisation-femme",
    password: "ALPHAF25",
    titre: "Séminaire d'alphabétisation arabe",
    enseignant: "Mu'allima Dounia",
    description: "Corrections et explications du livre d’alphabétisation Al-Iqraiyyah.",
    tags: ["Arabe", "Débutant"],
    zoomUrl: ZOOM_LINK,
    //pdfView: "assets/Livre-dalphabetisation-iqraiyyah-2025.pdf",
    replays: [
    { titre: "Cours du 28/04", url: "https://ton-lien-ici" },
  ],

    supports: [
      { titre: "Fiche n°1 — bâ, tâ, thâ et voyelles courtes",
        cours: "https://www.youtube.com/watch?v=telKHgVI3cw",
        correction: "https://www.youtube.com/watch?v=1a8Deyyr4MM",
        pdf: "assets/alpha/Fiche 1.pdf"},
      { titre: "Fiche n°2 — bâ, tâ, thâ et tanwîn",
        cours: "https://www.youtube.com/watch?v=kbGpVe481qU",
        correction: "https://www.youtube.com/watch?v=PZ_BLGF5Vyw",
        pdf: "assets/alpha/Fiche 2.pdf"},
      { titre: "Fiche n°3 — bâ, tâ, thâ et voyelles longues",
        cours: "https://www.youtube.com/watch?v=W_1VXnDcWVA",
        correction: "https://www.youtube.com/watch?v=bzGV8lp8G3Y",
        pdf: "assets/alpha/Fiche 3.pdf"},
      { titre: "Fiche n°4 — djîm, hâ et khâ",
        cours: "https://www.youtube.com/watch?v=eI7Iu2QGe5w",
        correction: "https://www.youtube.com/watch?v=Wab5xt4Tv6A",
        pdf: "assets/alpha/Fiche 4.pdf"},
      { titre: "Fiche n°5 — dâl, dhâl, râ, zay et soukoûn (P1)",
        cours: "https://www.youtube.com/watch?v=SPujRXH5wi",
        correction: "https://www.youtube.com/watch?v=dW4ZMgQcmME",
        pdf: "assets/alpha/Fiche 5.pdf"},
      { titre: "Fiche n°6 — dâl, dhâl, râ, zay et soukoûn (P2)",
        cours: "https://www.youtube.com/watch?v=SPujRXH5wi",
        correction: "https://www.youtube.com/watch?v=Fj58XweaRXk",
        pdf: "assets/alpha/Fiche 6.pdf"},
      { titre: "Fiche n°7 — sîn, chîn et chaddah",
        cours: "https://www.youtube.com/watch?v=YBR9s2cxj6o",
        correction: "https://www.youtube.com/watch?v=bhZwuEx1v4k",
        pdf: "assets/alpha/Fiche 7.pdf"},
      { titre: "Fiche n°8 — sâd, dâd, tâ’, thâ’ (P1)",
        cours: "https://www.youtube.com/watch?v=cy4BvAk55Aw",
        correction: "https://www.youtube.com/watch?v=7VTXvAiMSiI",
        pdf: "assets/alpha/Fiche 8.pdf"},
      { titre: "Fiche n°9 — sâd, dâd, tâ’, thâ’ (P2)",
        cours: "https://www.youtube.com/watch?v=uKYdQrzMuVo",
        correction: "https://www.youtube.com/watch?v=9ZjzYnXBUmI",
        pdf: "assets/alpha/Fiche 9.pdf"},
      { titre: "Fiche n°10 — ‘ayn et ghayn",
        cours: "https://www.youtube.com/watch?v=gw9jClQKlkY",
        correction: "https://www.youtube.com/watch?v=OyIAqtUhqGk",
        pdf: "assets/alpha/Fiche 10.pdf"},
      { titre: "Fiche n°11 — fâ’, qâf et kâf",
        cours: "https://www.youtube.com/watch?v=0hBvtgiluS0",
        correction: "https://www.youtube.com/watch?v=mq5hsDv3Rb4",
        pdf: "assets/alpha/Fiche 11.pdf"},
      { titre: "Fiche n°12 — lâm, mîm et nûn",
        cours: "https://www.youtube.com/watch?v=NUCfloC37bE",
        correction: "https://www.youtube.com/watch?v=00iblSVm0O4",
        pdf: "assets/alpha/Fiche 12.pdf"},
      { titre: "Fiche n°13 — hâ’, wâw et yâ’",
        cours: "https://www.youtube.com/watch?v=2OYUMgfRo-A",
        correction: "https://www.youtube.com/watch?v=vbfJzv2bdbg",
        pdf: "assets/alpha/Fiche 13.pdf"},
      { titre: "Fiche n°14 — Particularités coraniques",
        cours: "https://www.youtube.com/watch?v=krD5zZtSjMo",
        correction: "https://www.youtube.com/watch?v=wpATBOMbOrg",
        pdf: "assets/alpha/Fiche 14.pdf"},
      { titre: "Fiche n°15 — Ligatures (wasâlat)",
        cours: "https://www.youtube.com/watch?v=IdLoS2ezOrc",
        correction: "https://www.youtube.com/watch?v=ql_QWLYd7EA",
        pdf: "assets/alpha/Fiche 15.pdf"}
    ]
  },

  {
    slug: "tajwid",
    password: "TAJWID25",
    titre: "Séminaire de tajwid",
    enseignant: "Oustedh Joachim",
    description: "Cursus Tamhidi: Corrections et explications du livre Tajwīd Tadrīb al-Qāri, éditions Al-Iqraiyyah.",
    tags: ["Tajwid","Débutant"],
    //pdfView: "assets/Tajwid-indesign-2025-corrige.pdf",
    replays: [
    { titre: "Cours du 20/04", url: "https://youtu.be/DHISpnbHgZA" },
    { titre: "Cours du 25/04", url: "https://youtu.be/TTGXMrgaUbA" }
  ],

    supports: [
      { titre: "Fiche n°1",
        cours: "https://www.youtube.com/watch?v=8eNyslNGG4I",
        correction: "https://www.youtube.com/watch?v=kq2cwf0qKDc",
        pdf: "assets/tajwid/Fiche 1.pdf" },
      { titre: "Fiche n°1bis",
        cours: "https://www.youtube.com/watch?v=rDsHLVFIq2U",
        correction: "https://www.youtube.com/watch?v=ayOPIVXsPA4",
        pdf: "assets/tajwid/Fiche 1bis.pdf" },
      { titre: "Fiche n°2",
        cours: "https://www.youtube.com/watch?v=3HEtte7_hAU",
        correction: "https://www.youtube.com/watch?v=WY3Ep3g7gA4",
        pdf: "assets/tajwid/Fiche 2.pdf" },
      { titre: "Fiche n°3",
        cours: "https://www.youtube.com/watch?v=HTJqiHEVVQY",
        correction: "https://www.youtube.com/watch?v=uTOyNFmU-H0",
        pdf: "assets/tajwid/Fiche 3.pdf" },
      { titre: "Fiche n°4",
        cours: "https://www.youtube.com/watch?v=z9KfXcDrFng",
        correction: "https://www.youtube.com/watch?v=eeaDFigK_z0",
        pdf: "assets/tajwid/Fiche 4.pdf" },
      { titre: "Fiche n°5",
        cours: "https://www.youtube.com/watch?v=CW8W9Q1p2hg",
        correction: "https://www.youtube.com/watch?v=WscNzpGcOjI",
        pdf: "assets/tajwid/Fiche 5.pdf" },
      { titre: "Fiche n°6",
        cours: "https://www.youtube.com/watch?v=6h5rTCXTpGQ",
        correction: "https://www.youtube.com/watch?v=Zr2BjLYBjt8",
        pdf: "assets/tajwid/Fiche 6.pdf" },
      { titre: "Fiche n°7",
        cours: "https://www.youtube.com/watch?v=2G7zRQC2Qz0",
        correction: "https://www.youtube.com/watch?v=M0uee0GgT98",
        pdf: "assets/tajwid/Fiche 7.pdf" },
      { titre: "Fiche n°8",
        cours: "https://www.youtube.com/watch?v=PCp42JGxsYU",
        correction: "https://www.youtube.com/watch?v=entlBr8EfaI",
        pdf: "assets/tajwid/Fiche 8.pdf" },
      { titre: "Fiche n°9",
        cours: "https://www.youtube.com/watch?v=qm55loW0RMw",
        correction: "https://www.youtube.com/watch?v=PXnyq5yItDM",
        pdf: "assets/tajwid/Fiche 9.pdf" },
      { titre: "Fiche n°10",
        cours: "https://www.youtube.com/watch?v=LWXEsQe0Fsw",
        correction: "https://www.youtube.com/watch?v=OZvClypFBU0",
        pdf: "assets/tajwid/Fiche 10.pdf" },
      { titre: "Fiche n°11",
        cours: "https://www.youtube.com/watch?v=g2N9VYnL6IY",
        correction: "https://www.youtube.com/watch?v=xs3Wkm6h8as",
        pdf: "assets/tajwid/Fiche 11.pdf" },
      { titre: "Fiche n°12",
        cours: "https://www.youtube.com/watch?v=Z4m4zNh1B0M",
        correction: "https://www.youtube.com/watch?v=DOsXtWAFvBk",
        pdf: "assets/tajwid/Fiche 12.pdf" },
      { titre: "Fiche n°13",
        cours: "https://www.youtube.com/watch?v=_bUfHvXjdn4",
        pdf: "assets/tajwid/Fiche 13.pdf"},
      { titre: "Fiche n°14",
        cours: "https://www.youtube.com/watch?v=YDl0DbWFq80",
        correction: "https://www.youtube.com/watch?v=1wZRhGHUVHc",
        pdf: "assets/tajwid/Fiche 14.pdf" },
      { titre: "Fiche n°15",
        cours: "https://www.youtube.com/watch?v=TSOqquy_yB4",
        correction: "https://www.youtube.com/watch?v=9s52bO5VO6A",
        pdf: "assets/tajwid/Fiche 15.pdf" }
    ]
  },

];
